# Generated by Django 5.2.8 on 2025-11-12 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(help_text='Apenas números', max_length=11, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('perfil', models.CharField(choices=[('Fiscal', 'Fiscal'), ('Coordenador', 'Coordenador'), ('Gestor Contrato', 'Gestor Contrato')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CentroResponsabilidade',
            fields=[
                ('cod_cr', models.IntegerField(help_text='Código do Centro de Responsabilidade', primary_key=True, serialize=False)),
                ('nome_cr', models.CharField(max_length=255)),
                ('endereco_cr', models.CharField(blank=True, max_length=500, null=True)),
                ('secretaria_responsavel', models.CharField(max_length=100)),
                ('postos_trab_previstos', models.IntegerField(blank=True, help_text='Postos previstos no contrato', null=True)),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_coordenadores', to='afericao_app.perfilusuario')),
                ('fiscal_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_fiscais', to='afericao_app.perfilusuario')),
                ('gestor_contrato', models.ForeignKey(blank=True, help_text='Gestor a ser notificado por e-mail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_gestores', to='afericao_app.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Afericao',
            fields=[
                ('cod_afericao', models.CharField(help_text='Ex: 20251112900 (AAAAMMDD + Cod_CR)', max_length=20, primary_key=True, serialize=False)),
                ('data_afericao', models.DateTimeField(auto_now_add=True, help_text='Data/hora da criação do registro')),
                ('data_ultima_revisao', models.DateTimeField(blank=True, help_text='Data/hora da última revisão (Requisito D+1)', null=True)),
                ('status_revisao', models.BooleanField(default=False, help_text='Controla se a aferição ainda pode ser revisada')),
                ('postos_prev', models.IntegerField(help_text='Postos previstos (puxado do CR)')),
                ('postos_ocup', models.IntegerField(help_text='Postos ocupados na data')),
                ('postos_obs', models.TextField(blank=True, null=True)),
                ('serv_nota', models.IntegerField(choices=[(1, '1 - Péssimo'), (2, '2 - Ruim'), (3, '3 - Regular'), (4, '4 - Bom'), (5, '5 - Ótimo')], help_text="Nota para 'As dependências foram limpas?'")),
                ('mat_qt_nota', models.IntegerField(choices=[(1, '1 - Péssimo'), (2, '2 - Ruim'), (3, '3 - Regular'), (4, '4 - Bom'), (5, '5 - Ótimo')], help_text="Nota para 'Quantidade de materiais atendeu?'")),
                ('mat_ql_nota', models.IntegerField(choices=[(1, '1 - Péssimo'), (2, '2 - Ruim'), (3, '3 - Regular'), (4, '4 - Bom'), (5, '5 - Ótimo')], help_text="Nota para 'Qualidade está como prevista?'")),
                ('mat_rep_nota', models.IntegerField(choices=[(1, '1 - Péssimo'), (2, '2 - Ruim'), (3, '3 - Regular'), (4, '4 - Bom'), (5, '5 - Ótimo')], help_text="Nota para 'Reposição foi dentro do necessário?'")),
                ('mat_obs', models.TextField(blank=True, help_text='Observações gerais de materiais de consumo', null=True)),
                ('uso_maq', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
                ('maq_obs', models.TextField(blank=True, help_text='Caso afirmativo, qual máquina e onde?', null=True)),
                ('uso_epi', models.CharField(choices=[('Sim', 'Sim'), ('Parcial', 'Parcial'), ('Não', 'Não')], max_length=10)),
                ('epi_obs', models.TextField(blank=True, null=True)),
                ('desempenho_serv', models.FloatField(blank=True, editable=False, null=True)),
                ('desempenho_mat_qt', models.FloatField(blank=True, editable=False, null=True)),
                ('desempenho_mat_ql', models.FloatField(blank=True, editable=False, null=True)),
                ('desempenho_mat_rep', models.FloatField(blank=True, editable=False, null=True)),
                ('centro_responsabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afericao_app.centroresponsabilidade')),
                ('fiscal', models.ForeignKey(help_text='Fiscal que realizou a aferição', on_delete=django.db.models.deletion.PROTECT, to='afericao_app.perfilusuario')),
            ],
            options={
                'verbose_name': 'Aferição',
                'verbose_name_plural': 'Aferições',
                'ordering': ['-data_afericao'],
            },
        ),
    ]
