# Generated by Django 5.2.8 on 2025-11-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afericao_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('Fiscal de Equipamento', 'Fiscal de Equipamento'), ('Coordenador', 'Coordenador'), ('Gestor Contrato', 'Gestor Contrato'), ('Fiscal', 'Fiscal')], max_length=50),
        ),
    ]
