# Generated by Django 5.2.8 on 2025-11-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afericao_app', '0002_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroresponsabilidade',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centroresponsabilidade',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
