# Generated by Django 5.2.8 on 2025-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afericao_app', '0003_centroresponsabilidade_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afericao',
            name='data_afericao',
            field=models.DateTimeField(help_text='Data da aferição (pode ser retroativa)'),
        ),
    ]
